export const GET_CURRENCIES = 'GET_CURRENCIES'
export const ALL_ARQ_CURRENCIES_USD = 'ALL_ARQ_CURRENCIES_USD'
export const ALL_VACH_CURRENCIES_USD = 'ALL_VACH_CURRENCIES_USD'
export const ALL_ARQ_CURRENCIES_EUR = 'ALL_ARQ_CURRENCIES_EUR'
export const ALL_VACH_CURRENCIES_EUR = 'ALL_VACH_CURRENCIES_EUR'


